sudo: required

language: node_js

services:
  - docker

before_install:
  - docker build -t foobert/gc3-lookup lookup

install:
  - echo install

script:
  - echo script

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push foobert/gc3-lookup;
    fi
