version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker build -t foobert/gc3 lookup
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS
         docker push foobert/gc3

